Add StatusCodeException type and getStatusCodeException function.
Squashed commit of the following:

commit d528d8f0d585746403385b8494e945f36563dd08
Author: Toshio Ito <debug.ito@gmail.com>
Date:   Thu Apr 21 14:55:26 2022 +0900

    Ran ormolu

commit a8d2ec84ff9dfd891b791ba6d371689c3f308018
Author: Toshio Ito <debug.ito@gmail.com>
Date:   Thu Apr 21 14:54:54 2022 +0900

    Add a test case for getStatusCodeException.

commit b680caf188da68a20f1ccc8d8347429bfe7d7b18
Author: Toshio Ito <debug.ito@gmail.com>
Date:   Thu Apr 21 14:42:37 2022 +0900

    StatusCodeException: use IgnoreResponse instead of L.Response

    That way, we can use methods from HttpResponse to inspect the IgnoreResponse.

commit fc820c22a119bcffb0a6d46aa0eb8d9b4eaeaef2
Author: Toshio Ito <debug.ito@gmail.com>
Date:   Thu Apr 21 14:33:24 2022 +0900

    Add StatusCodeException and getStatusCodeException.